
Class HS.Custom.SampleData.HL7.test Extends %RegisteredObject
{

/// XData for HL7 Inbound
XData HL7InboundTestData
{
<text>
Copy test data into this XDATA block
</text>
}

/// test

/// XData for HL7 Transform
XData HL7TransformTestData
{
<text>
Copy test data into this XDATA block
</text>
}

/// XDATA for HL7 Interface Items
XData HL7InterfaceProduction
{
<text>
<Items>

<Item Name="HS.IHE.XDSb.Registry.Services" Category="" ClassName="HS.IHE.XDSb.Registry.Services" PoolSize="0" Enabled="true" Foreground="false" Comment="" LogTraceEvents="false" Schedule="">
  </Item>
  <Item Name="HS.IHE.XDSb.Repository.Process" Category="" ClassName="HS.IHE.XDSb.Repository.Process" PoolSize="1" Enabled="true" Foreground="false" Comment="" LogTraceEvents="false" Schedule="">
  </Item>

</Items>

</text>
}

}

